import type { Metadata } from "next";
import {Arima } from 'next/font/google'
import "./globals.css";
import next from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arima = Arima({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arima.className}>
        {children}
      </body>
    </html>
  );
}
